/**
 * PDF Branding Utilities
 * Adds RealCare branding (logo, headers, footers) to PDF exports
 */

// RealCare brand colors
export const BRAND_COLORS = {
  primary: '#4F46E5',      // brand-600 indigo
  primaryDark: '#4338CA',  // brand-700
  secondary: '#1E293B',    // slate-800
  accent: '#10B981',       // green-500
  warning: '#F59E0B',      // yellow-500
  danger: '#EF4444',       // red-500
  light: '#F1F5F9',        // slate-100
  white: '#FFFFFF',
  black: '#0F172A',        // slate-900
};

// RealCare logo as SVG path (simplified house + check mark icon)
export const LOGO_SVG_PATH = `
M12 3L2 12h3v9h6v-6h2v6h6v-9h3L12 3z
M10 10h4v4h-4z
`;

// PDF dimensions (A4 in mm)
export const PDF_DIMENSIONS = {
  width: 210,
  height: 297,
  margin: {
    top: 25,
    bottom: 25,
    left: 20,
    right: 20,
  },
  contentWidth: 170, // 210 - 20 - 20
};

interface BrandingOptions {
  title: string;
  subtitle?: string;
  date?: Date;
  reportType?: 'contract' | 'reality' | 'timeline' | 'general';
  includeQRCode?: boolean;
}

/**
 * Add header with RealCare branding to PDF
 */
export function addPdfHeader(
  pdf: {
    setFontSize: (size: number) => void;
    setTextColor: (r: number, g: number, b: number) => void;
    setFillColor: (r: number, g: number, b: number) => void;
    rect: (x: number, y: number, w: number, h: number, style: string) => void;
    text: (text: string, x: number, y: number, options?: { align?: string }) => void;
    setFont: (font: string, style?: string) => void;
    addImage: (data: string, format: string, x: number, y: number, w: number, h: number) => void;
  },
  options: BrandingOptions
): number {
  const { margin, width, contentWidth } = PDF_DIMENSIONS;

  // Top brand bar
  pdf.setFillColor(79, 70, 229); // brand-600
  pdf.rect(0, 0, width, 12, 'F');

  // Logo text (since we can't easily add SVG, use text logo)
  pdf.setFontSize(20);
  pdf.setTextColor(79, 70, 229);
  pdf.setFont('helvetica', 'bold');
  pdf.text('RealCare', margin.left, margin.top);

  // Tagline
  pdf.setFontSize(8);
  pdf.setTextColor(100, 116, 139); // slate-500
  pdf.setFont('helvetica', 'normal');
  pdf.text('Korean Real Estate Assistant', margin.left + 35, margin.top);

  // Report type badge
  const reportTypeLabels: Record<string, string> = {
    contract: 'CONTRACT ANALYSIS',
    reality: 'REALITY CHECK REPORT',
    timeline: 'MOVE-IN TIMELINE',
    general: 'REPORT',
  };
  const reportLabel = reportTypeLabels[options.reportType || 'general'];
  pdf.setFontSize(8);
  pdf.setTextColor(255, 255, 255);
  pdf.setFillColor(79, 70, 229);
  const labelWidth = pdf.text(reportLabel, 0, 0).length || 40;
  pdf.rect(width - margin.right - 35, margin.top - 5, 35, 6, 'F');
  pdf.text(reportLabel, width - margin.right - 33, margin.top - 1);

  // Title
  pdf.setFontSize(16);
  pdf.setTextColor(30, 41, 59); // slate-800
  pdf.setFont('helvetica', 'bold');
  pdf.text(options.title, margin.left, margin.top + 12);

  // Subtitle
  if (options.subtitle) {
    pdf.setFontSize(10);
    pdf.setTextColor(100, 116, 139);
    pdf.setFont('helvetica', 'normal');
    pdf.text(options.subtitle, margin.left, margin.top + 18);
  }

  // Date
  const dateStr = (options.date || new Date()).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  pdf.setFontSize(9);
  pdf.setTextColor(148, 163, 184); // slate-400
  pdf.text(dateStr, width - margin.right, margin.top + 12, { align: 'right' });

  // Divider line
  pdf.setFillColor(226, 232, 240); // slate-200
  pdf.rect(margin.left, margin.top + 22, contentWidth, 0.5, 'F');

  // Return Y position where content should start
  return margin.top + 30;
}

/**
 * Add footer with branding to PDF
 */
export function addPdfFooter(
  pdf: {
    setFontSize: (size: number) => void;
    setTextColor: (r: number, g: number, b: number) => void;
    setFillColor: (r: number, g: number, b: number) => void;
    rect: (x: number, y: number, w: number, h: number, style: string) => void;
    text: (text: string, x: number, y: number, options?: { align?: string }) => void;
    setFont: (font: string, style?: string) => void;
    internal: { getNumberOfPages: () => number };
    setPage: (page: number) => void;
  },
  totalPages?: number
): void {
  const { margin, width, height } = PDF_DIMENSIONS;
  const pages = totalPages || pdf.internal.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    pdf.setPage(i);

    // Footer divider
    pdf.setFillColor(226, 232, 240);
    pdf.rect(margin.left, height - margin.bottom - 5, width - margin.left - margin.right, 0.3, 'F');

    // Disclaimer
    pdf.setFontSize(7);
    pdf.setTextColor(148, 163, 184);
    pdf.setFont('helvetica', 'italic');
    pdf.text(
      'This report is generated by AI and is for reference only. Consult professionals for legal advice.',
      margin.left,
      height - margin.bottom
    );

    // Page number
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Page ${i} of ${pages}`, width - margin.right, height - margin.bottom, { align: 'right' });

    // Brand footer
    pdf.setFontSize(8);
    pdf.setTextColor(79, 70, 229);
    pdf.setFont('helvetica', 'bold');
    pdf.text('RealCare', width / 2, height - margin.bottom + 5, { align: 'center' });
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(148, 163, 184);
    pdf.text('| AI Real Estate Assistant', width / 2 + 12, height - margin.bottom + 5);
  }
}

/**
 * Add a section header
 */
export function addSectionHeader(
  pdf: {
    setFontSize: (size: number) => void;
    setTextColor: (r: number, g: number, b: number) => void;
    setFillColor: (r: number, g: number, b: number) => void;
    rect: (x: number, y: number, w: number, h: number, style: string) => void;
    text: (text: string, x: number, y: number) => void;
    setFont: (font: string, style?: string) => void;
  },
  title: string,
  y: number,
  color: 'primary' | 'success' | 'warning' | 'danger' = 'primary'
): number {
  const { margin, contentWidth } = PDF_DIMENSIONS;

  const colors: Record<string, [number, number, number]> = {
    primary: [79, 70, 229],
    success: [16, 185, 129],
    warning: [245, 158, 11],
    danger: [239, 68, 68],
  };

  const [r, g, b] = colors[color];

  // Section bar
  pdf.setFillColor(r, g, b);
  pdf.rect(margin.left, y, 3, 6, 'F');

  // Section title
  pdf.setFontSize(12);
  pdf.setTextColor(30, 41, 59);
  pdf.setFont('helvetica', 'bold');
  pdf.text(title, margin.left + 6, y + 5);

  return y + 12;
}

/**
 * Add text content with automatic wrapping
 */
export function addTextContent(
  pdf: {
    setFontSize: (size: number) => void;
    setTextColor: (r: number, g: number, b: number) => void;
    text: (text: string, x: number, y: number, options?: { maxWidth?: number }) => void;
    setFont: (font: string, style?: string) => void;
    splitTextToSize: (text: string, maxWidth: number) => string[];
  },
  text: string,
  y: number,
  options: {
    fontSize?: number;
    color?: [number, number, number];
    fontStyle?: 'normal' | 'bold' | 'italic';
    indent?: number;
  } = {}
): number {
  const { margin, contentWidth } = PDF_DIMENSIONS;
  const {
    fontSize = 10,
    color = [51, 65, 85], // slate-700
    fontStyle = 'normal',
    indent = 0,
  } = options;

  pdf.setFontSize(fontSize);
  pdf.setTextColor(...color);
  pdf.setFont('helvetica', fontStyle);

  const lines = pdf.splitTextToSize(text, contentWidth - indent);
  pdf.text(lines, margin.left + indent, y);

  // Return new Y position (approximate line height)
  return y + lines.length * (fontSize * 0.4 + 1);
}

/**
 * Add a risk item with severity indicator
 */
export function addRiskItem(
  pdf: {
    setFontSize: (size: number) => void;
    setTextColor: (r: number, g: number, b: number) => void;
    setFillColor: (r: number, g: number, b: number) => void;
    rect: (x: number, y: number, w: number, h: number, style: string) => void;
    text: (text: string, x: number, y: number, options?: { maxWidth?: number }) => void;
    setFont: (font: string, style?: string) => void;
    splitTextToSize: (text: string, maxWidth: number) => string[];
  },
  risk: {
    clause: string;
    explanation: string;
    severity: string;
    suggestion: string[];
  },
  y: number,
  index: number
): number {
  const { margin, contentWidth } = PDF_DIMENSIONS;

  // Severity colors
  const severityColors: Record<string, [number, number, number]> = {
    High: [239, 68, 68],
    Medium: [245, 158, 11],
    Low: [16, 185, 129],
  };
  const color = severityColors[risk.severity] || severityColors.Low;

  // Background box
  pdf.setFillColor(248, 250, 252); // slate-50
  const boxHeight = 25; // Will be adjusted
  pdf.rect(margin.left, y, contentWidth, boxHeight, 'F');

  // Severity indicator bar
  pdf.setFillColor(...color);
  pdf.rect(margin.left, y, 3, boxHeight, 'F');

  // Risk number and severity badge
  pdf.setFontSize(10);
  pdf.setTextColor(...color);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`#${index + 1}`, margin.left + 6, y + 5);

  pdf.setFontSize(7);
  pdf.setTextColor(255, 255, 255);
  pdf.setFillColor(...color);
  pdf.rect(margin.left + 15, y + 1, 18, 5, 'F');
  pdf.text(risk.severity.toUpperCase(), margin.left + 17, y + 4.5);

  // Clause (truncated)
  pdf.setFontSize(9);
  pdf.setTextColor(30, 41, 59);
  pdf.setFont('helvetica', 'bold');
  const clauseText = risk.clause.length > 80 ? risk.clause.substring(0, 80) + '...' : risk.clause;
  pdf.text(clauseText, margin.left + 6, y + 11);

  // Explanation
  pdf.setFontSize(8);
  pdf.setTextColor(71, 85, 105); // slate-600
  pdf.setFont('helvetica', 'normal');
  const explanationLines = pdf.splitTextToSize(risk.explanation, contentWidth - 12);
  const limitedLines = explanationLines.slice(0, 2);
  pdf.text(limitedLines, margin.left + 6, y + 17);

  return y + boxHeight + 5;
}

/**
 * Add a score display with visual indicator
 */
export function addScoreDisplay(
  pdf: {
    setFontSize: (size: number) => void;
    setTextColor: (r: number, g: number, b: number) => void;
    setFillColor: (r: number, g: number, b: number) => void;
    setDrawColor: (r: number, g: number, b: number) => void;
    rect: (x: number, y: number, w: number, h: number, style: string) => void;
    circle: (x: number, y: number, r: number, style: string) => void;
    text: (text: string, x: number, y: number, options?: { align?: string }) => void;
    setFont: (font: string, style?: string) => void;
  },
  score: number,
  label: string,
  y: number
): number {
  const { margin, contentWidth, width } = PDF_DIMENSIONS;
  const centerX = width / 2;

  // Score color based on value
  const getScoreColor = (s: number): [number, number, number] => {
    if (s >= 80) return [16, 185, 129];   // green
    if (s >= 60) return [34, 197, 94];    // light green
    if (s >= 40) return [245, 158, 11];   // yellow
    if (s >= 20) return [249, 115, 22];   // orange
    return [239, 68, 68];                  // red
  };

  const color = getScoreColor(score);

  // Score circle background
  pdf.setFillColor(248, 250, 252);
  pdf.setDrawColor(...color);
  // Draw arc approximation for progress circle (simplified)
  pdf.rect(centerX - 25, y, 50, 50, 'F');

  // Score number
  pdf.setFontSize(28);
  pdf.setTextColor(...color);
  pdf.setFont('helvetica', 'bold');
  pdf.text(score.toString(), centerX, y + 28, { align: 'center' });

  // Label
  pdf.setFontSize(10);
  pdf.setTextColor(100, 116, 139);
  pdf.setFont('helvetica', 'normal');
  pdf.text(label, centerX, y + 40, { align: 'center' });

  // Score bar
  pdf.setFillColor(226, 232, 240);
  pdf.rect(margin.left + 20, y + 55, contentWidth - 40, 6, 'F');
  pdf.setFillColor(...color);
  pdf.rect(margin.left + 20, y + 55, (contentWidth - 40) * (score / 100), 6, 'F');

  return y + 70;
}
