/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContractRouteImport } from './routes/contract'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIndexRouteImport } from './routes/agent/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AgentRegisterRouteImport } from './routes/agent/register'
import { Route as AgentListingsRouteImport } from './routes/agent/listings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractRoute = ContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRegisterRoute = AgentRegisterRouteImport.update({
  id: '/agent/register',
  path: '/agent/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentListingsRoute = AgentListingsRouteImport.update({
  id: '/agent/listings',
  path: '/agent/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculators': typeof CalculatorsRoute
  '/checkout': typeof CheckoutRoute
  '/contract': typeof ContractRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/subscription': typeof SubscriptionRoute
  '/timeline': typeof TimelineRoute
  '/wallet': typeof WalletRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/listings': typeof AgentListingsRoute
  '/agent/register': typeof AgentRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculators': typeof CalculatorsRoute
  '/checkout': typeof CheckoutRoute
  '/contract': typeof ContractRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/subscription': typeof SubscriptionRoute
  '/timeline': typeof TimelineRoute
  '/wallet': typeof WalletRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/listings': typeof AgentListingsRoute
  '/agent/register': typeof AgentRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculators': typeof CalculatorsRoute
  '/checkout': typeof CheckoutRoute
  '/contract': typeof ContractRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/subscription': typeof SubscriptionRoute
  '/timeline': typeof TimelineRoute
  '/wallet': typeof WalletRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/users': typeof AdminUsersRoute
  '/agent/listings': typeof AgentListingsRoute
  '/agent/register': typeof AgentRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculators'
    | '/checkout'
    | '/contract'
    | '/forgot-password'
    | '/login'
    | '/plans'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/signals'
    | '/subscription'
    | '/timeline'
    | '/wallet'
    | '/admin/agents'
    | '/admin/users'
    | '/agent/listings'
    | '/agent/register'
    | '/admin'
    | '/agent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculators'
    | '/checkout'
    | '/contract'
    | '/forgot-password'
    | '/login'
    | '/plans'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/signals'
    | '/subscription'
    | '/timeline'
    | '/wallet'
    | '/admin/agents'
    | '/admin/users'
    | '/agent/listings'
    | '/agent/register'
    | '/admin'
    | '/agent'
  id:
    | '__root__'
    | '/'
    | '/calculators'
    | '/checkout'
    | '/contract'
    | '/forgot-password'
    | '/login'
    | '/plans'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/signals'
    | '/subscription'
    | '/timeline'
    | '/wallet'
    | '/admin/agents'
    | '/admin/users'
    | '/agent/listings'
    | '/agent/register'
    | '/admin/'
    | '/agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorsRoute: typeof CalculatorsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContractRoute: typeof ContractRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TimelineRoute: typeof TimelineRoute
  WalletRoute: typeof WalletRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AgentListingsRoute: typeof AgentListingsRoute
  AgentRegisterRoute: typeof AgentRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract': {
      id: '/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof ContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/register': {
      id: '/agent/register'
      path: '/agent/register'
      fullPath: '/agent/register'
      preLoaderRoute: typeof AgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/listings': {
      id: '/agent/listings'
      path: '/agent/listings'
      fullPath: '/agent/listings'
      preLoaderRoute: typeof AgentListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorsRoute: CalculatorsRoute,
  CheckoutRoute: CheckoutRoute,
  ContractRoute: ContractRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  SubscriptionRoute: SubscriptionRoute,
  TimelineRoute: TimelineRoute,
  WalletRoute: WalletRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AgentListingsRoute: AgentListingsRoute,
  AgentRegisterRoute: AgentRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentIndexRoute: AgentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
