/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ContractRouteImport } from './routes/contract'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractRoute = ContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculators': typeof CalculatorsRoute
  '/contract': typeof ContractRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/subscription': typeof SubscriptionRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculators': typeof CalculatorsRoute
  '/contract': typeof ContractRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/subscription': typeof SubscriptionRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculators': typeof CalculatorsRoute
  '/contract': typeof ContractRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/subscription': typeof SubscriptionRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculators'
    | '/contract'
    | '/settings'
    | '/signals'
    | '/subscription'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculators'
    | '/contract'
    | '/settings'
    | '/signals'
    | '/subscription'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/calculators'
    | '/contract'
    | '/settings'
    | '/signals'
    | '/subscription'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorsRoute: typeof CalculatorsRoute
  ContractRoute: typeof ContractRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract': {
      id: '/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof ContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorsRoute: CalculatorsRoute,
  ContractRoute: ContractRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  SubscriptionRoute: SubscriptionRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
